---
- name: "Wordpress Installation"
  hosts: wphosts
  become: true
  vars:
    domain: learnatease.xyz
  vars_files:
    - mysql.vars
  tasks:    
      
    - name: Install Apache, PHP, MySQL
      yum:
        name:
          - httpd
          - mariadb-server
          - MySQL-python
          - php
          - php-mysql
        state: present

    - name: Start services
      service:
        name: mariadb
        state: restarted
        enabled: yes
    
    - name: "Mariadb - Setting Root Password"
      ignore_errors: true
      mysql_user:
        login_user: "root"
        login_password: ""
        name: root
        password: "{{ mysql_root_password }}"
        host_all: true
            
    - name: "Mariadb - Removing Anonymous Users"
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: ""
        host_all: yes
        state: absent
            
    - name: "Mariadb - Creating Database"
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ mysql_database }}"
        state: present
        
    - name: "mariadb - Creating User"
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        host: "localhost"
        priv: "{{ mysql_database }}.*:ALL"
        state: present

    - name: "Wordpress installation - Downloading"
      get_url:
        url: https://wordpress.org/wordpress-4.7.8.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: "Wordpress - Extracting"
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: true
            
    - name: "Wordpress - Copying Contents to documentroot"
      copy:
        src: /tmp/wordpress/
        dest: "/var/www/html/{{ domain }}"
        remote_src: true
        owner: apache
        group: apache
    
    - name: "Wordpress - Copying wp-config.php template"
      template:
        src: wp-config.php.tmpl
        dest: "/var/www/html/{{ domain }}/wp-config.php"
        owner: apache
        group: apache
            
    - name: "Wordpress - Post Installation clean up"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/wordpress.tar.gz
        - /tmp/wordpress
    - name: "Apache start"
      service:
        name: httpd
        state: present
